### ISSUE TITLE
How to test on custom data?

### ISSUE THREAD

**Issue by PeiLin-666** [heyuanYao-pku/MoConVQ#5]
Nice work!
In the task of "Motion Reconstruction:, you have already given a sequence to test;)  But How can I test it on more sequence? How do you transfer the data to .bvh? The skeleton seems to be different from the one from SMPL.
Thank you!

**Comment by PeiLin-666** [comment]
Closed.
For the one who also wants to test on custom data:
I use https://github.com/KosukeFukazawa/CharacterAnimationTools#13-load-animation-from-amass to transfer the amass data to bvh. Although the skeleton of smpl/smplh is different from the skeleton used in MoConVQ, it is easy to retarget and here are some tips:
1. delete all of the joints of hands
2. merge the spine2 and spine3  and delete spine3
3. merge the neck and head  and delete head
4. copy the HIERARCHY of MoConVQ .bvh to your .bvh. Check whether the rotation is Xrotation Yrotation Zrotation or Zrotation Yrotation Xrotation.

**Comment by BinLee26** [comment]
Could you kindly share how you approached merging the rotations in your code?
